spring.application.name=JobHub
#Config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/JobHub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123

#@Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
#Config logging
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd hh:mm:ss.SSS} -  %highlight(%-5level) - %cyan(%logger{50}) - %green(%msg%n)
logging.logback.rollingpolicy.max-file-size=20MB
logging.logback.rollingpolicy.max-history=30
logging.level.root=INFO
logging.level.ra.demo = INFO

#Config jwt
jwt-secret = daylachuoibimatduocsudungdetaorajwt
jwt.access-expiration-ms = 1800000
jwt.refresh-expiration-ms = 604800000